//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn should be constructed by valid steps.
        /// </summary>
        internal static string Error_EmptySteps {
            get {
                return ResourceManager.GetString("Error_EmptySteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GameField should be constructed by valid cells and dimension.
        /// </summary>
        internal static string Error_GameFieldCtor {
            get {
                return ResourceManager.GetString("Error_GameFieldCtor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimension should be more than zero.
        /// </summary>
        internal static string Error_InvalidDimension {
            get {
                return ResourceManager.GetString("Error_InvalidDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No players should be null.
        /// </summary>
        internal static string Error_NullPlayers {
            get {
                return ResourceManager.GetString("Error_NullPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game ended.
        /// </summary>
        internal static string Info_GameEnd {
            get {
                return ResourceManager.GetString("Info_GameEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game started.
        /// </summary>
        internal static string Info_GameStart {
            get {
                return ResourceManager.GetString("Info_GameStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History rolled.
        /// </summary>
        internal static string Info_HistoryRoll {
            get {
                return ResourceManager.GetString("Info_HistoryRoll", resourceCulture);
            }
        }
    }
}
