//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wpf.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geame finished.
        /// </summary>
        public static string Log_GameFinish {
            get {
                return ResourceManager.GetString("Log_GameFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game started.
        /// </summary>
        public static string Log_GameStart {
            get {
                return ResourceManager.GetString("Log_GameStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Game.
        /// </summary>
        public static string Wpf_ButtonContent_Finish {
            get {
                return ResourceManager.GetString("Wpf_ButtonContent_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        public static string Wpf_ButtonContent_Redo {
            get {
                return ResourceManager.GetString("Wpf_ButtonContent_Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Game.
        /// </summary>
        public static string Wpf_ButtonContent_Start {
            get {
                return ResourceManager.GetString("Wpf_ButtonContent_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string Wpf_ButtonContent_Undo {
            get {
                return ResourceManager.GetString("Wpf_ButtonContent_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls.
        /// </summary>
        public static string Wpf_Header_Controls {
            get {
                return ResourceManager.GetString("Wpf_Header_Controls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Status.
        /// </summary>
        public static string Wpf_Header_GameStatus {
            get {
                return ResourceManager.GetString("Wpf_Header_GameStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your side.
        /// </summary>
        public static string Wpf_TextBlock_ChooseSide {
            get {
                return ResourceManager.GetString("Wpf_TextBlock_ChooseSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robot Time (ms).
        /// </summary>
        public static string Wpf_TextBlock_RobotTime {
            get {
                return ResourceManager.GetString("Wpf_TextBlock_RobotTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait for the game to start.
        /// </summary>
        public static string WpfPlalyer_StartStatus {
            get {
                return ResourceManager.GetString("WpfPlalyer_StartStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep jumping.
        /// </summary>
        public static string WpfPlayer_JumpTurn_Continue {
            get {
                return ResourceManager.GetString("WpfPlayer_JumpTurn_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the cell for the required jump.
        /// </summary>
        public static string WpfPlayer_JumpTurn_Start {
            get {
                return ResourceManager.GetString("WpfPlayer_JumpTurn_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the cell for the turn.
        /// </summary>
        public static string WpfPlayer_SimpleTurn {
            get {
                return ResourceManager.GetString("WpfPlayer_SimpleTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The winner is.
        /// </summary>
        public static string WpfPlayer_WinnerIs {
            get {
                return ResourceManager.GetString("WpfPlayer_WinnerIs", resourceCulture);
            }
        }
    }
}
